# Generated by Django 5.0.4 on 2024-05-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentacar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
